--3�� ȣ��, ����, ȸ������ �����ͺ��̽� �Է�

--ȣ�� ���̺� ��ü ����
DROP TABLE Hotel
CASCADE CONSTRAINTS;

--ȣ�� ������ ����
DROP SEQUENCE SEQ_HOTEL;

--ȣ�� ������ ����
CREATE SEQUENCE SEQ_HOTEL
INCREMENT BY 1
START WITH 1;

--ȣ�� ���̺� ���� (���߿� ���̺� ���� spl���Ϸ� ��Ƶ־���)
CREATE TABLE HOTEL(
SEQ NUMBER(8) PRIMARY KEY,
NAME VARCHAR2(50) NOT NULL,
PLACE VARCHAR2(20) NOT NULL,
ADDR VARCHAR2(100) NOT NULL,
USE_COUNT NUMBER(8) NOT NULL,
RATING NUMBER(3,2) NOT NULL,
HOTEL_IMG VARCHAR2(200),
HOTEL_IMG_REAL VARCHAR2(200)
);

--ȣ�� ���̺� Ȯ�ο�

SELECT *
FROM HOTEL;

--ȣ�� ���̺� �� ����
DELETE 
FROM HOTEL;


--ȣ�� �߰�
INSERT INTO HOTEL(SEQ, NAME, PLACE, ADDR, USE_COUNT, RATING)
VALUES (SEQ_HOTEL.NEXTVAL, '�Ŷ�ȣ��', '����', '����Ư���� �߱� ���浿 ��ȣ�� 249', 242, 4.8);

INSERT INTO HOTEL(SEQ, NAME, PLACE, ADDR, USE_COUNT, RATING)
VALUES (SEQ_HOTEL.NEXTVAL, '����ƾ ����ȣ�� ����', '����', '����Ư���� �߱� 106 �Ұ���', 170, 4.6);

INSERT INTO HOTEL(SEQ, NAME, PLACE, ADDR, USE_COUNT, RATING)
VALUES (SEQ_HOTEL.NEXTVAL, '�ñ״Ͽ� ����', '����', '����Ư���� ���ı� ���6�� �ø��ȷ� 300', 134, 4.9);

INSERT INTO HOTEL(SEQ, NAME, PLACE, ADDR, USE_COUNT, RATING)
VALUES (SEQ_HOTEL.NEXTVAL, '�Ķ���̽� ȣ�� �λ�', '�λ�', '�λ걤���� �ؿ�뱸 �ߵ� �ؿ���غ��� 296', 64, 4.1);

INSERT INTO HOTEL(SEQ, NAME, PLACE, ADDR, USE_COUNT, RATING)
VALUES (SEQ_HOTEL.NEXTVAL, '���̸��ȣ��', '�λ�', '�λ걤���� �ؿ�뱸 �쵿 �ؿ���غ���209������ 27', 50, 4.0);

INSERT INTO HOTEL(SEQ, NAME, PLACE, ADDR, USE_COUNT, RATING)
VALUES (SEQ_HOTEL.NEXTVAL, '�� ����ġ�� ����Ʈ', '��õ', '������ ��õ�� ȿ�ڵ� ȿ�ڷ� 136', 80, 3.7);

INSERT INTO HOTEL(SEQ, NAME, PLACE, ADDR, USE_COUNT, RATING)
VALUES (SEQ_HOTEL.NEXTVAL, '��õ ���轼���ν�ȣ��', '��õ', '������ ��õ�� ��ȭ�� 265-3', 114, 4.2);

INSERT INTO HOTEL(SEQ, NAME, PLACE, ADDR, USE_COUNT, RATING)
VALUES (SEQ_HOTEL.NEXTVAL, '�󸶴� ���� ȣ��', '����', '���������� ������ ���� ���� 127', 77, 3.6);

INSERT INTO HOTEL(SEQ, NAME, PLACE, ADDR, USE_COUNT, RATING)
VALUES (SEQ_HOTEL.NEXTVAL, '������ ȣ��', '����', '���������� ������ ���� 537-2', 31, 3.2);

INSERT INTO HOTEL(SEQ, NAME, PLACE, ADDR, USE_COUNT, RATING)
VALUES (SEQ_HOTEL.NEXTVAL, '���ְ���ȣ��', '����', '����ϵ� ���ֽ� �ϻ걸 �߾ӵ� ���ְ���5�� 44-5', 44, 2.8);

INSERT INTO HOTEL(SEQ, NAME, PLACE, ADDR, USE_COUNT, RATING)
VALUES (SEQ_HOTEL.NEXTVAL, '������', '����', '����ϵ� ���ֽ� ����� 33-6 KR', 61, 4.6);

INSERT INTO HOTEL(SEQ, NAME, PLACE, ADDR, USE_COUNT, RATING)
VALUES (SEQ_HOTEL.NEXTVAL, '�ҳ�į ����', '����', '���󳲵� ������ �ѷ��� �������� 111', 128, 4.5);

INSERT INTO HOTEL(SEQ, NAME, PLACE, ADDR, USE_COUNT, RATING)
VALUES (SEQ_HOTEL.NEXTVAL, '���纣��ȣ��', '����', '���󳲵� ������ ��ȣ�� �ſ��� 496-25', 119, 4.1);

INSERT INTO HOTEL(SEQ, NAME, PLACE, ADDR, USE_COUNT, RATING)
VALUES (SEQ_HOTEL.NEXTVAL, '��ũ��� �����̾� ��õ', '��õ', '��õ������ ������ �۵�1�� �����þƴ�� 165', 161, 4.7);

INSERT INTO HOTEL(SEQ, NAME, PLACE, ADDR, USE_COUNT, RATING)
VALUES (SEQ_HOTEL.NEXTVAL, '�׽�Ʈ ȣ��', '��õ', '��õ������ �߱� ������ �����ؾȳ��� 19-5', 131, 4.2);

INSERT INTO HOTEL(SEQ, NAME, PLACE, ADDR, USE_COUNT, RATING)
VALUES (SEQ_HOTEL.NEXTVAL, '������ȣ��', '����', '������ ���ʽ� ������ ���ش�� 3705', 110, 3.1);

INSERT INTO HOTEL(SEQ, NAME, PLACE, ADDR, USE_COUNT, RATING)
VALUES (SEQ_HOTEL.NEXTVAL, '��ũ�����Ʈ', '����', '������ ������ ������ ��ȭ�� 950-39', 109, 3.4);

INSERT INTO HOTEL(SEQ, NAME, PLACE, ADDR, USE_COUNT, RATING)
VALUES (SEQ_HOTEL.NEXTVAL, 'ȣ�ڽø��콺', '����', '����Ư����ġ�� ���ֽ� ���� 2334-4', 151, 4.4);

INSERT INTO HOTEL(SEQ, NAME, PLACE, ADDR, USE_COUNT, RATING)
VALUES (SEQ_HOTEL.NEXTVAL, '�ֽ���ȣ��', '����', '����Ư����ġ�� ���ֽ� ���Ե� 1443-2', 118, 4.1);

INSERT INTO HOTEL(SEQ, NAME, PLACE, ADDR, USE_COUNT, RATING)
VALUES (SEQ_HOTEL.NEXTVAL, '��Ÿ��ȣ��', '���', '��걤���� ���� ��굿 ���߷� 65', 51, 2.4);

-------------------------------------------------------------------------------------------------

-- ���� ������ ���̽� 

-- #1 �Ŷ�ȣ��
INSERT INTO ROOM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '����Ͻ� �𷰽���', 1, 310000, 2);

INSERT INTO ROOM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '�̱���ťƼ�� �׷��� �𷰽���', 1, 620000, 4);

INSERT INTO ROOM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '���������� ����Ʈ��', 1, 1100000, 6);

-- #2 ����ƾ ����ȣ�� ����
INSERT INTO ROOM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '�𷰽� ŷ �Խ�Ʈ��', 2, 280000, 2);

INSERT INTO ROOM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '�̱���ťƼ�� �Խ�Ʈ��', 2, 440000, 3);

INSERT INTO ROOM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '�ο� ����Ʈ��', 2, 560000, 4);

-- #3 �ñ״Ͽ� ����
INSERT INTO ROOM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '�׷��� �𷰽� ��', 3, 340000, 2);

INSERT INTO ROOM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '�𷰽� ����Ʈ ��', 3, 620000, 2);

INSERT INTO ROOM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '�ڸ��� ��Ÿ�� ����Ʈ', 3, 2400000, 2);

-- #4 �Ķ���̽� ȣ�� �λ�
INSERT INTO ROOM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '�𷰽� �� ��Ƽ��', 4, 120000, 2);

INSERT INTO ROOM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '�̱���ťƼ�� �𷰽� �� ���Ǻ�', 4, 180000, 2);

INSERT INTO ROOM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '�ִϾ� ����Ʈ ����� ���Ǻ�', 4, 310000, 2);

-- #5 ���̸��ȣ��
INSERT INTO ROOM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '���Ĵٵ� ��', 5, 80000, 2);

INSERT INTO ROOM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, 'HIGH �𷰽� ��', 5, 140000, 2);

INSERT INTO ROOM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '����Ʈ ��', 5, 220000, 4);

-- #6 �� ����ġ�� ����Ʈ
INSERT INTO ROOM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '�ѽ�(�µ�)', 6, 60000, 2);

INSERT INTO ROOM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '���Ĵٵ� �����', 6, 80000, 2);

-- #7 ��õ ���轼���ν�ȣ��

INSERT INTO ROOM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '���Ĵٵ� �����', 7, 100000, 2);

INSERT INTO ROOM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '���丮�� �����', 7, 150000, 2);

INSERT INTO ROOM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '������ ����Ʈ��', 7, 230000, 4);

-- #8 �󸶴� ����ȣ��

INSERT INTO ROOM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '�ζ�� �����', 8, 90000, 2);

INSERT INTO ROOM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '�Ҹ���� ŷ��', 8, 150000, 2);

INSERT INTO ROOM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '�󸶴� ����Ʈ��', 8, 290000, 6);

-- #9 ������ ȣ��

INSERT INTO ROOM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '�𷰽� �����', 9, 170000, 2);

INSERT INTO ROOM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '�������� �����', 9, 242000, 2);

INSERT INTO ROOM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '�������� ����Ʈ ��Ʈ�Ͽ콺', 9, 1650000, 6);

-- #10 ��Ŭ���� ȣ��

INSERT INTO ROOM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '�𷰽� ŷ', 10, 70000, 2);

INSERT INTO ROOM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '�����̾� ����', 10, 120000, 2);

-- #11 ȣ�� �ٶ���

INSERT INTO ROOM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '���Ĵٵ� �����', 11, 90000, 2);

INSERT INTO ROOM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '����Ʈ��', 11, 150000, 2);

-- #12 �ҳ�į ����

INSERT INTO ROMM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '���Ĵٵ� ��', 12, 130000, 2);

INSERT INTO ROOM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '�̱���ťƼ�� ��', 12, 240000, 2);

INSERT INTO ROOM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, 'ž ����Ʈ ��', 12, 460000, 4);

-- #13 ���纣��ȣ�� 

INSERT INTO ROMM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '���Ĵٵ� ��', 13, 70000, 2);

INSERT INTO ROOM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '�𷰽� ��', 13, 90000, 2);

INSERT INTO ROOM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '����Ʈ��', 13, 200000, 4);

-- #14 ��ũ��� �����̾� ��õ

INSERT INTO ROMM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '��Ʃ��� �𷰽� ��', 14, 240000, 2);

INSERT INTO ROOM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '���丮�� �𷰽� ��', 14, 280000, 2);

INSERT INTO ROOM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '��Ʃ��� �йи�', 14, 480000, 4);

-- #15 �׽�Ʈ ȣ��

INSERT INTO ROMM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '���Ĵٵ� ��', 15, 120000, 2);

INSERT INTO ROOM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '�𷰽� ��', 15, 140000, 2);

INSERT INTO ROOM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '�ĳ�� ����Ʈ��', 15, 310000, 4);

-- #16 ������ȣ��

INSERT INTO ROMM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '���Ĵٵ� ���� ��', 16, 70000, 2);

INSERT INTO ROOM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '���丮�� ����Ʈ ��', 16, 190000, 2);

INSERT INTO ROOM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '�ξ� ����Ʈ ��', 16, 800000, 4);

-- #17 ��ũ�����Ʈ

INSERT INTO ROMM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '���Ÿ� ���� ��', 17, 130000, 2);

INSERT INTO ROOM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '�ִϾ� ����Ʈ ��', 17, 250000, 4);

-- #18 ȣ�ڽø��콺

INSERT INTO ROMM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '���Ĵٵ� ��', 18, 50000, 2);

INSERT INTO ROOM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '���丮�� ��', 18, 70000, 2);

INSERT INTO ROOM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '����Ʈ ��', 18, 120000, 2);

-- #19 �ֽ���ȣ��

INSERT INTO ROMM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '���Ĵٵ� ��', 19, 40000, 2);

INSERT INTO ROOM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, 'Ű�� ��', 19, 80000, 2);

INSERT INTO ROOM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '�ξ� ����Ʈ ��', 19, 310000, 6);

-- #20 ��Ÿ��ȣ��

INSERT INTO ROMM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '���Ĵٵ� ��', 20, 60000, 2);

INSERT INTO ROOM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '���Ĵٵ� ���̷�', 20, 80000, 2);

INSERT INTO ROOM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '����Ʈ ��', 20, 170000, 4);

--------------------------------------------------------------------------------
--ȸ�� DB

INSERT INTO BM_MEMBER(SEQ, ID, PWD, NAME, PHONENUM, EMAIL, AUTH, DEL)
VALUES (SEQ_BM_MEMBER.NEXTVAL, 'wjh', 'beatcamp', '������', '010-7143-7691', 'corsa94@naver.com', 0, 0);

INSERT INTO BM_MEMBER(SEQ, ID, PWD, NAME, PHONENUM, EMAIL, AUTH, DEL)
VALUES (SEQ_BM_MEMBER.NEXTVAL, 'lsb', 'beatcamp', '�̼���', '010-1111-1111', 'lsb@naver.com', 0, 0);

INSERT INTO BM_MEMBER(SEQ, ID, PWD, NAME, PHONENUM, EMAIL, AUTH, DEL)
VALUES(SEQ_BM_MEMBER.NEXTVAL, 'wjh', 'beatcamp', '������', '010-1111-1111', 'wonjongta@naver.com', 0, 0);

INSERT INTO BM_MEMBER(SEQ, ID, PWD, NAME, PHONENUM, EMAIL, AUTH, DEL)
VALUES (SEQ_BM_MEMBER.NEXTVAL, 'kyn', 'beatcamp', '������', '010-1111-1111', 'kimyuna@naver.com', 0, 0);

INSERT INTO BM_MEMBER(SEQ, ID, PWD, NAME, PHONENUM, EMAIL, AUTH, DEL)
VALUES (SEQ_BM_MEMBER.NEXTVAL, 'ljw', 'beatcamp', '������', '010-1111-1111', 'ljh@naver.com', 0, 0);

INSERT INTO BM_MEMBER(SEQ, ID, PWD, NAME, PHONENUM, EMAIL, AUTH, DEL)
VALUES (SEQ_BM_MEMBER.NEXTVAL, 'admin', 'beatcamp', '������', '02-111-1111', 'admin@admin.com', 1, 0);